---
name: ci
on: [push, pull_request]
jobs:
  code-check:
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:v1.36.0"
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/code-check.sh
  shell-check:
    runs-on: ubuntu-latest
    # Github runners have shellcheck already
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/shellcheck.sh
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: ./scripts/unit-test.sh
  compile:
    needs: [unit-test, shell-check, code-check]
    runs-on: ubuntu-latest
    container: "golang:1.15-buster"
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/compile.sh
  release:
    needs: [unit-test, shell-check, code-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: ./scripts/release.sh
        env:
          IMAGE_TAG: ${GITHUB_REF}
          DOCKER_USER: simonsargeant
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
          DOCKER_HOST: ""
